mapping = {'Pepper bell  Bacterial spot': None,
            'Pepper bell  healthy': None,
            'Potato  Early blight': None,
            'Potato  Late blight': None,
            'Potato  healthy': None,
            'Tomato Bacterial spot': None,
            'Tomato Early blight': 'Tomatoes that have early blight require immediate attention before the disease takes over the plants. Thoroughly spray the plant (bottoms of leaves also) with Bonide Liquid Copper Fungicide concentrate or Bonide Tomato & Vegetable. Both of these treatments are organic. If possible time applications so that 12 hours of dry weather follows applications. A day after treatment, remove the lower branches with sharp razor blade knife. Clean your knife with rubbing alcohol before trimming the next plant to prevent the spread of the disease. Repeat fungicide treatments every 7 to 14 days. Read the label instructions carefully. Do not spray pesticides, fungicides, fertilizers or herbicides when it’s in the high 80’s or 90; you can damage your plants. Water your plants the day before spraying, hydration is important!',
            'Tomato Late blight': None,
            'Tomato Leaf Mold': None,
            'Tomato Septoria leaf spot': None,
            'Tomato Spider mites Two spotted spider mite': None,
            'Tomato  Target Spot': None,
            'Tomato YellowLeaf  Curl Virus': """Use a neonicotinoid insecticide, such as dinotefuran (Venom) imidacloprid (AdmirePro, Alias, Nuprid, Widow, and others) or thiamethoxam (Platinum), as a soil application or through the drip irrigation system at transplanting of tomatoes or peppers.""",
            'Tomato mosaic virus': None,
            'Tomato healthy': None}